---
title: "Making websites"
---

This page outlines the process of making a basic website using R Markdown, and hosting that website on GitHub. The content assumes some familiarity with both of those. 

## Some slides

<script async class="speakerdeck-embed" data-id="e4897332b1e345e8a223b5e82fc61504" data-ratio="1.33333333333333" src="//speakerdeck.com/assets/embed.js"></script>
<div style="margin-bottom:5px"> <strong> <a href="https://speakerdeck.com/jeffgoldsmith/making-websites" title="Making websites" target="_blank">Making Websites</a> </strong> from <strong><a href="https://speakerdeck.com/jeffgoldsmith" target="_blank">Jeff Goldsmith</a></strong>. </div>

## Example

### Create a local directory

Naming structure (if this is a personal site vs anything else)

### Basic elements

index.Rmd

YAML

Site nav


### Common content

plain text

r code (remember you can run code here)

links (external and internal)

images (i like to keep these in a sub-folder; do whatever you want)


### R Project

(not necessary, but why not?)

(build site)


### Hosting on GitHub

(name for primary webpage)

(name for sub-pages)

Change settings to publish


### Tips for building websites

Keep content up-to-date

Copy structures from other websites


## Other materials

There's a lot of material online to help with making websites:

* RStudio's [guide](http://rmarkdown.rstudio.com/rmarkdown_websites.html)
* This [walk through](http://nickstrayer.me/RMarkdown_Sites_tutorial/)
* GitHub [Pages](https://pages.github.com)
