---
title: "Visualization and EDA"
---

Visualization and exploratory numerical analysis are the analytic components that immediately follow data wrangling. In addition to helping identify additional necessary wrangling steps, these are your first chance to explore the data in detail: you can explore patterns, identify trends, formulate hypotheses, and be surprised by preliminary findings. We'll discuss the elements of a good graphic before learning how to produce them, and then move on to tools for exploratory analyses using grouped data.  

With the completion of this topic, we will have covered quite a bit of ground -- a workflow for doing data science in a clear and reproducible way; tools for data wrangling; and and introduction to visualization and exploratory analysis. To tie these together, we'll finish this topic with a case study.

The topic is made up of the following components:

* [Visualization with `ggplot2`](visualization.html)
* [Exploratory analysis using `group_by`](exploratory_analysis.html)
* [Case study](case_study_viz_and_eda.html)

