---
title: "Visualization with `ggplot2`"
output:
  html_document: 
    toc: true
    toc_float: true
---

Good visualization is a critical step in data analysis. 

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  fig.width = 8,
  fig.height = 4
)
```

## Some slides

<script async class="speakerdeck-embed" data-id="77a37cf3dcb945a9abd2e09439158d07" data-ratio="1.33333333333333" src="//speakerdeck.com/assets/embed.js"></script>
<div style="margin-bottom:5px"> <strong> <a href="https://speakerdeck.com/jeffgoldsmith/dsi-visualization" title="Visualization" target="_blank">Visualization</a> </strong> from <strong><a href="https://speakerdeck.com/jeffgoldsmith" target="_blank">Jeff Goldsmith</a></strong>. </div><br>


## Example

New project for viz and EDA.

```{r weather_data_create, cache = TRUE}
library(tidyverse)
library(rnoaa)

weather = meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                              var = c("PRCP", "TMAX", "TMIN", "TAVG"), 
                              date_min = "2016-01-01",
                              date_max = "2017-01-01")

```

### stuff

```{r}
ggplot(weather, aes(x = tmax, y = tmin)) + geom_hex()

weather %>%
ggplot(aes(x = date, y = tmax, size = prcp, color = id)) + geom_point(alpha = .5) + facet_grid(.~id) + geom_smooth()
```



## Other materials

http://r4ds.had.co.nz/data-visualisation.html and http://r4ds.had.co.nz/graphics-for-communication.html; 

http://vita.had.co.nz/papers/layered-grammar.pdf

http://stat545.com/cm006_tibbles-dplyr-ggplot2.html and https://github.com/jennybc/ggplot2-tutorial

http://www.cookbook-r.com/Graphs/

http://shop.oreilly.com/product/0636920023135.do

http://varianceexplained.org/r/teach_ggplot2_to_beginners/

* [cheatsheet](https://www.rstudio.com/wp-content/uploads/2016/11/ggplot2-cheatsheet-2.1.pdf), which also has some tips for tidying.

http://www.jstor.org/stable/2683253?seq=1#page_scan_tab_contents  https://www.biostat.wisc.edu/~kbroman/presentations/graphs2017.pdf

https://www.biostat.wisc.edu/~kbroman/topten_worstgraphs/
