---
title: "Writing R Packages II"
output:
  html_document: 
    toc: true
    toc_float: true
---

If you write more than two functions, you need a package -- this will remind you what functions do and how they interact with each other, help you keep track of inputs and outputs, and, if you want to share you code, allow you to do so in a standard format. The [first part](writing_r_packages_i.html) of this module covered getting to a complete package from scratch; this module covers some important but more advanced issues in R package development.

This is the second module in the [Writing R Packages](topic_writing_r_packages.html) topic; the relevant slack channel is [here](https://p8105-fall2017.slack.com/messages/C86A5JU9L).

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
```


## Some slides

<script async class="speakerdeck-embed" data-id="3f91d97c70e641cea46366ac9d90c929" data-ratio="1.33333333333333" src="//speakerdeck.com/assets/embed.js"></script>
<div style="margin-bottom:5px"> <strong> <a href="https://speakerdeck.com/jeffgoldsmith/dsi-writing-functions" title="Writing Functions" target="_blank">Writing Functions</a> </strong> from <strong><a href="https://speakerdeck.com/jeffgoldsmith" target="_blank">Jeff Goldsmith</a></strong>. </div><br>


## Example

Keep working on the same package.

### Vignettes

Short vignette for the package; include as Rmd. 

### Search path

search(), MASS::select vs tidyverse::select

### NAMESPACE

Look at namespace file in package at various devel stages

### Checks

Run check on old version of package

### Tests 

Write a couple of simple tests





## Other materials

Many of these topics are touched on in the other materials for [writing R packages I](writing_r_packages_i.html); below we provide additional resources specific to the more specialized topics here. 

* The R Packages book is the best resource. There are chapters on
    * [What is a package?](http://r-pkgs.had.co.nz/package.html#package)
    * [NAMESPACE](http://r-pkgs.had.co.nz/namespace.html)
    * [Checks](http://r-pkgs.had.co.nz/check.html) 
    * [Tests](http://r-pkgs.had.co.nz/tests.html)
    * [Vignettes](http://r-pkgs.had.co.nz/vignettes.html)
    * [Data](http://r-pkgs.had.co.nz/data.html)
    * [Compiled code](http://r-pkgs.had.co.nz/src.html)
* The official guide to [Writing R Extensions](https://cran.r-project.org/doc/manuals/r-release/R-exts.html) also exists, although I'm not sure I exactly _recommend_ it ...

The code that I produced working examples in lecture is [here](...).
